project:
  type: website

website:
  title: "ADA Bayern"
  navbar:
    background: darkgreen
    left:
      #- product.qmd
      - text: "Aktuelle Workshopserien"
        menu:
        - text: "In Arbeit"
      - text: "Portfolio"
        menu: 
        - text: "Workshop Serie 4: Einzelbaumerkennung"
          href: workshops/ws4/WS4.qmd
        - text: "Workshop Serie 3: Daten-basierte Archivierung von Gerichtsakten"
          href: workshops/ws3/WS3.qmd
        - text: "Workshop Serie 2: Daten-basierte Archivierung von Gerichtsakten (Implementation)"
          href: workshops/ws2/WS2.qmd
        - text: "Workshop Serie 1: Daten-basierte Archivierung von Gerichtsakten"
          href: workshops/ws1/WS1.qmd
      - team.qmd
      - kontakt.qmd
      - impressum.qmd

  sidebar:
    - title: "Workshop Serie 4: Einzelbaumerkennung"
      style: "docked"
      background: light
      contents:
        - workshops/ws4/WS4.qmd
        - section: "Module"
          contents:
          - workshops/ws4/WS4_Modul_1.qmd
          - workshops/ws4/WS4_Modul_2.qmd
          - workshops/ws4/WS4_Modul_3.qmd

    - title: "Workshop Serie 3: Daten-basierte Archivierung von Gerichtsakten"
      style: "docked"
      background: light
      contents:
        - workshops/ws3/WS3.qmd
        - section: "Module"
          contents:
          - workshops/ws3/WS3_Modul_1.qmd
          - workshops/ws3/WS3_Modul_2.qmd
          - workshops/ws3/WS3_Modul_3.qmd

    - title: "Workshop Serie 2: Daten-basierte Archivierung von Gerichtsakten"
      style: "docked"
      background: light
      contents:
        - workshops/ws2/WS2.qmd
        - section: "Module"
          contents:
          - workshops/ws2/WS2_Modul_1.qmd
          - workshops/ws2/WS2_Modul_2.qmd
          - workshops/ws2/WS2_Modul_3.qmd
          - workshops/ws2/WS2_Modul_4.qmd

    - title: "Workshop Serie 1: Daten-basierte Archivierung von Gerichtsakten"
      style: "docked"
      background: light
      contents:
        - workshops/ws1/WS1.qmd
        - section: "Module"
          contents:
          - workshops/ws1/WS1_Modul_1.qmd
          - workshops/ws1/WS1_Modul_2.qmd
          - workshops/ws1/WS1_Modul_3.qmd
          - workshops/ws1/WS1_Modul_4.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false