project:
  type: book

book:
  title: "Angewandte Datenanalyse für die öffentliche Verwaltung"
  chapters:
    - index.qmd
    - Modul_1.qmd
    - Modul_2.qmd
    - Modul_3.qmd
    - Modul_4.qmd
    - references.qmd
  navbar:
    background: white

bibliography: references.bib

format:
  html:
    theme: flatly
    number-depth: 0



