project:
  type: book

book:
  title: "ADA-Oeffentliche-Verwaltung-Website"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    background: white

bibliography: references.bib

format:
  html:
    theme: flatly



