[[card]]
title = ""
content = "Beschäftigte im öffentlichen Sektor zum (besseren) Umgang mit Daten befähigen."
type = ""
color = "green"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Datenkompetenz stärken, und so zur Umsetzung von sinnvollen Datenprojekten beitragen."
type = ""
color = "lilac"
link={url="/impressum", text="Kontaktieren Sie uns"}

[[card]]
title = ""
content = "Anhand konkreter Beispiele aus der Verwaltungspraxis machen wir Digitalisierung greifbar und interaktiv erlebbar."
type = ""
color = "salmon"
link={url="/impressum", text="Kontaktieren Sie uns"}
