[[partner]]
name = "BERD@NFDI"
logo = "images/initiators/Logo_BERD-NFDI.png"
url = "https://berd.nfdi.de"


[[partner]]
name = "LMU Munich"
logo = "images/initiators/Logo_LMU.svg"
url = "https://www.lmu.de"

[[partner]]
name = "Bayerische Staatsministerium für Digitales"
logo = "images/initiators/logo_staatsregierung.png"
url = "https://www.stmd.bayern.de/ministerium/organisation/"

[[partner]]
name = "BERD@NFDI"
logo = "images/initiators/Logo_BERD-NFDI.png"
url = "https://berd.nfdi.de"


[[client]]
name = "BERD@NFDI"
logo = "images/initiators/Logo_BERD-NFDI.png"
url = "https://berd.nfdi.de"


[[client]]
name = "Bayerische Staatsministerium für Digitales"
logo = "images/initiators/logo_staatsregierung.png"
url = "https://www.stmd.bayern.de/ministerium/organisation/"

[[client]]
name = "LMU Munich"
logo = "images/initiators/Logo_LMU.svg"
url = "https://www.lmu.de"
