name: Zola on GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build only (PR)
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_DIR: public
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts --base-url https://ada-bayern.github.io/website/

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Build and deploy (main)
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          BUILD_DIR: public
          PAGES_BRANCH: gh-pages
          BUILD_FLAGS: --base-url https://ada-bayern.github.io/website/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
